export const surveySteps = [
  {
    id: 'gender-name',
    title: 'Apa gender dan siapa nama anak anda?',
    type: 'gender-name',
  },
  {
    id: 'age',
    title: 'Berapa umur anak Anda?',
    type: 'age-selection',
  },
  {
    id: 'personality',
    title: 'Capaian apa yang Anda inginkan terhadap anak Anda?',
    type: 'multiple-choice',
    options: [
      'Kemampuan akademik yang baik',
      'Keterampilan sosial dan emosional',
      'Kreativitas dan inovasi',
      'Kepercayaan diri tinggi',
      'Kemampuan problem solving',
      'Komunikasi yang efektif',
      'Kemandirian dalam belajar',
      'Lainnya',
    ],
  },
  {
    id: 'activities',
    title: 'Siapa yang sering menggunakan perangkat anak?',
    type: 'multiple-choice',
    options: [
      'Anak sendiri',
      'Orang tua',
      'Menggunakan bersama',
      'Pengasuh',
      'Saudara',
      'Lainnya',
    ],
  },
  {
    id: 'interests1',
    title: 'Apa harapan Anda kepada anak Anda?',
    type: 'multiple-choice',
    options: [
      'Tumbuh menjadi anak yang bahagia',
      'Memiliki kepercayaan diri yang tinggi',
      'Berhasil secara akademik',
      'Memiliki banyak teman dan mudah bergaul',
      'Kreatif dan inovatif dalam berpikir',
      'Mandiri dan bertanggung jawab',
      'Sehat fisik dan mental',
      'Memiliki karakter yang baik',
    ],
  },
  {
    id: 'interests2',
    title: 'Kegiatan apa yang paling disukai anak Anda?',
    type: 'multiple-choice',
    options: [
      'Menyanyi dan bercerita',
      'Mencari tahu hal baru',
      'Mendengarkan cerita',
      'Bermain dengan teman',
      'Menggambar dan mewarnai',
      'Bermain dengan mainan',
      'Belajar hal baru',
      'Lainnya',
    ],
  },
  {
    id: 'learning-difficulty',
    title: 'Apakah Anak Mengalami Kesulitan Dalam Belajar?',
    type: 'multiple-choice',
    options: [
      'Tidak ada kesulitan khusus',
      'Kesulitan konsentrasi',
      'Kesulitan memahami instruksi',
      'Kesulitan mengingat informasi',
      'Kesulitan dengan angka/matematika',
      'Kesulitan dengan huruf/membaca',
      'Kesulitan dengan motorik halus',
      'Lainnya',
    ],
  },
  {
    id: 'learning-method',
    title: 'Bagaimana metode belajar terbaik untuk anak Anda?',
    type: 'multiple-choice',
    options: [
      'Belajar sambil bermain',
      'Menggunakan gambar dan visual',
      'Mendengarkan musik dan lagu',
      'Praktek langsung dengan tangan',
      'Bercerita dan diskusi',
      'Menggunakan teknologi digital',
      'Lainnya',
    ],
  },
];

export type SurveyStep = (typeof surveySteps)[number];
