/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = 'bjmmuanqdewtshttwhvi';
export const publicAnonKey =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqbW11YW5xZGV3dHNodHR3aHZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1ODczMzAsImV4cCI6MjA3NTE2MzMzMH0.yLNfxBTkMS1tFQREnIGAYa_bD-mb9diNzNlZQLWbmWs';
